version: '3.2'

services:
  # This container depends on the config written by the configure container above, so it
  # sleeps for a second on startup to allow the configure container to run first.
  teleport:
    image: quay.io/gravitational/teleport-lab:10
    container_name: teleport
    entrypoint: /bin/sh
    hostname: luna.teleport
    command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport.d/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs

  # The bootstrap container generates certificates and then immediately exits.
  bootstrap:
    image: quay.io/gravitational/teleport-lab:10
    container_name: teleport-bootstrap
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/generate-certs.sh"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    depends_on:
      - teleport

  #
  # openssh is a demo of openssh node
  #
  openssh:
    image: quay.io/gravitational/teleport-lab:10
    container_name: openssh
    hostname: mars.openssh.teleport
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/start-sshd.sh"
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap

  #
  # term is a container with a terminal to try things out
  #
  term:
    image: quay.io/gravitational/teleport-lab:10
    hostname: term
    container_name: term
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    volumes:
      - certs:/mnt/shared/certs
    depends_on:
      - bootstrap

volumes:
  certs:
  data:
  config:
